Added a contributing guide document [9369]
eProsima/policies pull request #2
Opened 2020-09-21 14:15 UTC by imontesino

Signed-off-by: imontesino <monte.igna@gmail.com>

2020-09-21 14:39 UTC, MiguelCompany requested changes

2020-09-21 14:39 UTC, MiguelCompany commented on CONTRIBUTING.md
> +*Fast DDS* is an open source C++ implementation of the DDS (Data Distribution Service) standard of the OMG (Object
This is for all eProsima open source projects

2020-09-21 14:39 UTC, MiguelCompany commented on CONTRIBUTING.md
> +1. Submit your pull requests in separate branches. As for branch names, we normally use `features/*` for adding
```suggestion
1. Submit your pull requests in separate branches. As for branch names, we normally use `feature/*` for adding
```

2020-09-21 14:39 UTC, MiguelCompany commented on CONTRIBUTING.md
> +   we really appreciate your contributing effort. To be merged into the master branch o the releases, a pull request
```suggestion
   we really appreciate your contributing effort. To be merged into the master branch or the releases, a pull request
```

2020-09-21 14:39 UTC, MiguelCompany commented on CONTRIBUTING.md
> +
I think this does not belong here

2020-09-22 08:20 UTC, JLBuenoLopez-eProsima requested changes

2020-09-22 08:20 UTC, JLBuenoLopez-eProsima commented on CONTRIBUTING.md
> +   Docs](https://github.com/eProsima/Fast-RTPS-docs) documenting the added functionality.
It should not refer to a particular repository documentation. It should be generic.

2020-09-22 14:40 UTC, JLBuenoLopez-eProsima reviewed
Please, consider these comments

2020-09-22 14:40 UTC, JLBuenoLopez-eProsima commented on CONTRIBUTING.md
> +   As for branch names, we normally use `feature/*` for addingfunctionality or refactors, `hotfix/*` for small fixes,
```suggestion
   As for branch names, we normally use `feature/*` for adding functionality or refactors, `hotfix/*` for small fixes,
```

2020-09-22 14:40 UTC, JLBuenoLopez-eProsima commented on CONTRIBUTING.md
> +   Pull request with unsigned commits will not pass the automated checks until unsigned commits have been amended.
```suggestion
   Pull requests with unsigned commits will not pass the automated checks until unsigned commits have been amended.
```

2020-09-22 14:40 UTC, JLBuenoLopez-eProsima commented on CONTRIBUTING.md
> +   Origin (DCO)](https://developercertificate.org/).
Too long. Maybe consider splitting this sentence in two.

2020-09-22 14:40 UTC, JLBuenoLopez-eProsima commented on CONTRIBUTING.md
> +Please mind that by doing so, you accept to abide to the pull request process followed on this repository, meaning:
```suggestion
Please mind that by doing so, you accept to abide to the pull request process followed by eProsima, meaning:
```
These rules do not apply only to this repository, but also to all eProsima repositories

2020-09-22 14:40 UTC, JLBuenoLopez-eProsima commented on CONTRIBUTING.md
> +1. Code should be formatted according to our [Code Style Guide](https://github.com/eProsima/cpp-style), we also provide
```suggestion
1. Code should be formatted according to our [Code Style Guide](https://github.com/eProsima/cpp-style). We also provide
```

2020-09-22 14:40 UTC, JLBuenoLopez-eProsima commented on CONTRIBUTING.md
> +   We will be happy to help you and to improve each repository's instructions.
```suggestion
   We will be happy to help you and to improve the instructions for each repository if needed.
```

2020-09-23 13:43 UTC, JLBuenoLopez-eProsima approved these changes
LGTM

2020-09-25 11:42 UTC, MiguelCompany approved these changes

2020-09-25 11:43 UTC, merged